### ISSUE TITLE
need to update the heatmap tutorial to use mean shapes from SlicerMorph

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/Tutorials#16]
https://github.com/SlicerMorph/Tutorials/blob/main/heatmaps/Heatmaps.md
 unnecessarily complicates things by doing the mean model calculation in Morpho. it should just do the export mean shape from our GPA module. (load the 3D reference model, set up the PCA visualization, and then go to Data module, right click the TPS deformed model and export is as PLY).

**Comment by DiamondKMG** [comment]
I've added in how to export the models using  only slicer, but left in the R commands incase someone wants to use this tutorial, who has already done their analysis in R.
